[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"

# Compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# EVM version
evm_version = "paris"

# Remappings for imports
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Test settings
verbosity = 2
gas_reports = ["*"]

# File system permissions for deployment scripts
fs_permissions = [{ access = "read-write", path = "./deployments" }]

# RPC endpoints
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
